import { StyleSheet } from 'react-native';

import type { Theme } from '@/theme';

export const makeAskTraydStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingBottom: 12,
      backgroundColor: theme.colors.secondary,
    },
    headerBtn: {
      width: 36,
      height: 36,
      borderRadius: theme.radii.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.12)',
    },
    titleCol: { flex: 1, marginLeft: 2 },
    title: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    subtitle: {
      marginTop: 2,
      fontSize: 10,
      fontFamily: theme.fonts.mono,
      letterSpacing: 0.6,
      color: theme.colors.white,
      opacity: 0.75,
    },
    content: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 16 },
    blockWrap: { marginLeft: 40, marginTop: -6, marginBottom: 14, gap: 10 },
    typingRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 14,
    },
    typingBubble: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radii.lg,
      borderTopLeftRadius: 4,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    typingText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    emptyWrap: { paddingTop: 18, paddingRight: 12 },
    emptyIcon: {
      width: 52,
      height: 52,
      borderRadius: theme.radii.md,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.secondary,
    },
    emptyTitle: {
      marginTop: 22,
      fontSize: theme.typography.size.xxl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
      lineHeight: 32,
    },
    emptyText: {
      marginTop: 10,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      lineHeight: 22,
    },
    card: {
      alignSelf: 'stretch',
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
    },
    cardHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingTop: 14,
      paddingBottom: 12,
    },
    cardLabel: {
      flex: 1,
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    cardTotal: {
      fontSize: theme.typography.size.xl,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.text,
    },
    divider: { height: 1, backgroundColor: theme.colors.divider },
    itemRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
    },
    itemBody: { flex: 1, gap: 3 },
    itemTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
    dot: { width: 7, height: 7, borderRadius: 4 },
    dotDanger: { backgroundColor: theme.colors.error },
    dotWarn: { backgroundColor: theme.colors.warning },
    itemTitle: {
      flexShrink: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    itemSubtitle: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.mono,
      color: theme.colors.textMuted,
    },
    itemAmount: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.text,
    },
    textDanger: { color: theme.colors.error },
    textWarn: { color: theme.colors.warning },
    tableScroll: { paddingRight: 14 },
    tableRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    tableHeadRow: { paddingVertical: 9 },
    tableBodyRow: { paddingVertical: 11 },
    th: {
      fontSize: 9,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      color: theme.colors.textMuted,
    },
    td: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    tdFirst: { fontFamily: theme.fonts.semibold },
    tdNum: {
      textAlign: 'right',
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.text,
    },
    apprCard: {
      alignSelf: 'stretch',
      borderRadius: theme.radii.lg,
      borderWidth: 1.5,
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 12,
    },
    apprCardDone: { borderColor: theme.colors.creamBorder },
    apprHead: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
    apprTag: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: theme.radii.sm,
      backgroundColor: theme.colors.warningBg,
    },
    apprTagText: {
      fontSize: 9,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      color: theme.colors.warning,
    },
    apprSummary: {
      flex: 1,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
      lineHeight: 19,
    },
    apprRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 14,
      paddingVertical: 9,
    },
    apprLabel: {
      flex: 1,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.mono,
      color: theme.colors.textMuted,
    },
    apprValue: {
      flex: 1.4,
      textAlign: 'right',
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    apprActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
    apprBtn: {
      flex: 1,
      height: 42,
      borderRadius: theme.radii.md,
      alignItems: 'center',
      justifyContent: 'center',
    },
    apprApprove: { backgroundColor: theme.colors.secondary },
    apprApproveText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.onSecondary,
    },
    apprCancel: {
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surfaceMuted,
    },
    apprCancelText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    apprHint: {
      marginTop: 8,
      textAlign: 'center',
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.6,
      color: theme.colors.textMuted,
    },
    apprStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 12,
    },
    apprStatus: {
      flex: 1,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
    },
    apprStatusOk: { color: theme.colors.green },
    apprStatusOff: { color: theme.colors.textMuted },
    subBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: 18,
      paddingTop: 12,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: '#DDD8CC',
    },
    chatsPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      height: 30,
      paddingHorizontal: 14,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: '#DDD8CC',
      backgroundColor: theme.colors.white,
    },
    chatsPillText: {
      fontSize: 14,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.primary,
    },
    newChatBox: {
      width: 30,
      height: 30,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: '#DDD8CC',
      alignItems: 'center',
      justifyContent: 'center',
    },
    bellWrap: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bellBadge: {
      position: 'absolute',
      top: -2,
      right: -4,
      minWidth: 20,
      height: 20,
      paddingHorizontal: 5,
      borderRadius: 10,
      backgroundColor: '#C0392B',
      alignItems: 'center',
      justifyContent: 'center',
    },
    bellBadgeText: {
      fontSize: 12,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    userRow: {
      flexDirection: 'row',
      alignSelf: 'flex-end',
      alignItems: 'flex-start',
      gap: 8,
      maxWidth: '88%',
      marginBottom: 12,
    },
    userBubble: {
      flexShrink: 1,
      backgroundColor: theme.colors.secondary,
      paddingVertical: 12,
      paddingHorizontal: 15,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderBottomLeftRadius: 18,
      borderBottomRightRadius: 6,
    },
    userText: {
      fontSize: 16,
      lineHeight: 21.6,
      fontFamily: theme.fonts.regular,
      color: theme.colors.white,
    },
    userAvatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    userAvatarText: {
      fontSize: 11,
      fontFamily: theme.fonts.bold,
      color: theme.colors.secondary,
    },
    botRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      marginBottom: 12,
    },
    botAvatar: {
      width: 30,
      height: 30,
      borderRadius: 10,
      marginTop: 2,
      backgroundColor: theme.colors.secondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    botBubble: {
      flex: 1,
      minWidth: 0,
      backgroundColor: theme.colors.white,
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderTopLeftRadius: 6,
      borderTopRightRadius: 20,
      borderBottomLeftRadius: 20,
      borderBottomRightRadius: 20,
      gap: 12,
    },
    botText: {
      fontSize: 15,
      lineHeight: 20.7,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    draftWrap: { gap: 8 },
    draftCard: {
      borderWidth: 1,
      borderColor: '#E3DED3',
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: '#FBF9F4',
    },
    draftHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: '#E3DED3',
    },
    draftHeadText: {
      flex: 1,
      fontFamily: theme.fonts.monoBold,
      fontSize: 10.5,
      letterSpacing: 1.05,
      color: theme.colors.secondary,
    },
    draftChip: {
      height: 22,
      paddingHorizontal: 8,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FCEBD1',
    },
    draftChipOff: { backgroundColor: theme.colors.surfaceMuted },
    draftChipText: {
      fontSize: 10,
      letterSpacing: 0.6,
      fontFamily: theme.fonts.semibold,
      color: '#9A5B0A',
    },
    draftChipTextOff: { color: theme.colors.textMuted },
    draftRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 10,
      paddingLeft: 14,
      paddingRight: 38,
    },
    draftRowLine: { height: 1, backgroundColor: '#EFEAE0' },
    draftSummary: {
      paddingVertical: 10,
      paddingHorizontal: 14,
      fontSize: 14.5,
      lineHeight: 20,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.secondary,
    },
    draftLabel: {
      fontSize: 14.5,
      fontFamily: theme.fonts.regular,
      color: '#5a6577',
    },
    draftValue: {
      flex: 1,
      textAlign: 'right',
      fontSize: 14.5,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    draftPencil: { position: 'absolute', right: 12 },
    draftPrimary: {
      height: 46,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
      shadowColor: theme.colors.primary,
      shadowOpacity: 0.25,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 3,
    },
    draftPrimaryText: {
      fontSize: 14,
      fontFamily: theme.fonts.bold,
      color: theme.colors.onPrimary,
    },
    draftCancelBtn: { alignSelf: 'center', paddingVertical: 2 },
    draftCancelText: {
      fontSize: 13,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.textMuted,
    },
    draftCancelled: {
      fontSize: 13,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.textMuted,
    },
    doneBody: {
      alignItems: 'center',
      gap: 8,
      paddingVertical: 18,
      paddingHorizontal: 14,
    },
    doneTick: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: '#DCE8E0',
      alignItems: 'center',
      justifyContent: 'center',
    },
    doneTitle: {
      fontSize: 17,
      fontFamily: theme.fonts.bold,
      color: theme.colors.secondary,
      textAlign: 'center',
    },
    doneSub: {
      fontSize: 13,
      fontFamily: theme.fonts.regular,
      color: '#5a6577',
      textAlign: 'center',
    },
    composerBar: {
      marginHorizontal: 18,
      paddingTop: 22,
      borderTopWidth: 1,
      borderTopColor: '#DDD8CC',
      backgroundColor: theme.colors.background,
    },
    composer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 52,
      borderRadius: 26,
      backgroundColor: theme.colors.white,
      borderWidth: 1,
      borderColor: '#DDD8CC',
      paddingHorizontal: 8,
    },
    composerInput: {
      flex: 1,
      minWidth: 0,
      maxHeight: 110,
      paddingVertical: 12,
      paddingLeft: 8,
      fontSize: 16,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    composerSend: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.primary,
    },
    composerSendOff: { backgroundColor: '#E8E3D8' },
    drawerBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)' },
    drawerPanel: {
      flex: 1,
      backgroundColor: theme.colors.surface,
      borderTopRightRadius: theme.radii.lg,
      borderBottomRightRadius: theme.radii.lg,
      paddingHorizontal: 18,
    },
    drawerHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      paddingBottom: 14,
    },
    drawerLabel: {
      marginTop: 10,
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    drawerClose: {
      width: 38,
      height: 38,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    drawerNew: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 11,
      paddingHorizontal: 12,
      marginBottom: 4,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surfaceMuted,
    },
    drawerNewText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    drawerGroup: {
      marginTop: 14,
      marginBottom: 2,
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    drawerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 11,
    },
    drawerRowText: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    drawerRowTextActive: { color: theme.colors.primary },
    drawerEmpty: {
      paddingVertical: 16,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
  });

export default makeAskTraydStyles;
