import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme';

export const makeCertificationStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    centered: { alignItems: 'center', justifyContent: 'center' },

    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    back: { marginRight: 8 },
    eyebrow: {
      fontSize: 11,
      letterSpacing: 1.5,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
    },
    title: {
      marginTop: 4,
      fontSize: 24,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    subtitle: {
      marginTop: 6,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
      lineHeight: 20,
    },

    content: { paddingHorizontal: 20, paddingTop: 10 },

    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      padding: 16,
      marginBottom: 12,
    },
    cardHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    cardType: {
      flex: 1,
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    badge: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: theme.radii.pill,
      backgroundColor: theme.colors.surfaceMuted,
    },
    badgeText: {
      fontSize: 10,
      letterSpacing: 1,
      fontFamily: theme.fonts.monoBold,
    },
    cardMeta: {
      marginTop: 6,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
    },
    cardExpiry: {
      marginTop: 10,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
    },
    cardExpiryStrong: { fontFamily: theme.fonts.semibold, color: theme.colors.text },
    cardFoot: {
      marginTop: 12,
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    viewLink: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.primary,
    },

    addBtn: { marginTop: 4, marginBottom: 8 },

    warnBox: {
      flexDirection: 'row',
      gap: 10,
      backgroundColor: theme.colors.errorBg,
      borderRadius: theme.radii.lg,
      padding: 14,
      marginTop: 8,
    },
    warnText: {
      flex: 1,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.text,
      lineHeight: 19,
    },
    warnStrong: { fontFamily: theme.fonts.bold },

    empty: { alignItems: 'center', paddingHorizontal: 32, paddingTop: 48 },
    emptyIcon: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
      textAlign: 'center',
    },
    emptyText: {
      marginTop: 8,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: 20,
    },

    banner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: theme.radii.lg,
      padding: 16,
      marginBottom: 16,
    },
    bannerText: {
      flex: 1,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
    },
    infoCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      paddingHorizontal: 16,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      gap: 12,
    },
    infoDivider: {
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.divider,
    },
    infoLabel: {
      fontSize: 11,
      letterSpacing: 1,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
    },
    infoValue: {
      flexShrink: 1,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
      textAlign: 'right',
    },

    fieldLabel: {
      fontSize: 11,
      letterSpacing: 1,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
      marginBottom: 8,
    },
    req: { color: theme.colors.primary },
    select: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      paddingHorizontal: 14,
      paddingVertical: 14,
    },
    selectText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.text,
    },
    selectPlaceholder: { color: theme.colors.placeholder },
    dateRow: { flexDirection: 'row', gap: 12 },
    dateCol: { flex: 1 },
    photoTile: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: theme.colors.borderMuted,
      paddingHorizontal: 14,
      paddingVertical: 16,
    },
    photoTileText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
    },
    hint: {
      marginTop: 12,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
      textAlign: 'center',
    },

    sheetBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    sheetCard: {
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingTop: 12,
      paddingBottom: 24,
    },
    sheetHandle: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.colors.borderMuted,
      marginBottom: 8,
    },
    sheetRow: {
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.divider,
    },
    sheetRowText: {
      fontSize: 15,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
  });
