import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme';

const onNavyMuted = 'rgba(255,255,255,0.6)';
const onNavyFaint = 'rgba(255,255,255,0.5)';
const cardFill = 'rgba(255,255,255,0.06)';
const cardBorder = 'rgba(255,255,255,0.12)';

export const makeDashboardStyles = (theme: Theme) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.colors.background },
    scrollContent: { flexGrow: 1 },
    certBanner: { marginHorizontal: 16, marginTop: 16, marginBottom: 4 },
    body: {
      flexGrow: 1,
      backgroundColor: theme.colors.background,
      marginTop: -24,
      paddingBottom: 8,
    },
  });

export const makeDashboardHeaderStyles = (theme: Theme) =>
  StyleSheet.create({
    header: {
      backgroundColor: theme.colors.secondary,
      paddingHorizontal: 20,
      paddingBottom: 34,
    },
    topRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    actions: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    bellBtn: {
      width: 44,
      height: 44,
      backgroundColor: cardFill,
      borderRadius:12,
      padding:4,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bellBadge: {
      position: 'absolute',
      top: -6,
      right: -7,
      minWidth: 16,
      height: 16,
      paddingHorizontal: 4,
      borderRadius: 8,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: theme.colors.secondary,
    },
    bellBadgeText: {
      color: theme.colors.onPrimary,
      fontSize: 9,
      fontFamily: theme.fonts.bold,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: theme.colors.secondary,
      fontFamily: theme.fonts.bold,
      fontSize: 15,
    },
    avatarAlert: {
      position: 'absolute',
      top: -4,
      right: -4,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: theme.colors.error,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: theme.colors.secondary,
    },
    avatarAlertText: {
      color: theme.colors.white,
      fontSize: 10,
      lineHeight: 13,
      fontFamily: theme.fonts.bold,
    },
    eyebrow: {
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.primary,
    },
    greeting: {
      marginTop: 16,
      fontSize: theme.typography.size.xxl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    subtitle: { marginTop: 2, fontSize: theme.typography.size.md, lineHeight: 22 },
    subtitleStrong: {
      fontFamily: theme.fonts.semibold,
      color: theme.colors.white,
      fontSize: theme.typography.size.md,
    },
    subtitleMuted: {
      fontFamily: theme.fonts.regular,
      color: onNavyMuted,
      fontSize: theme.typography.size.md,
    },
    subtitleReg: {
      fontFamily: theme.fonts.semibold,
      color: theme.colors.primary,
      fontSize: theme.typography.size.md,
    },
    statsRow: { flexDirection: 'row', gap: 12, marginTop: 16 },
    statCard: {
      flex: 1,
      borderRadius: 12,
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: cardFill,
      borderWidth: 1,
      borderColor: cardBorder,
    },
    statLabel: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: onNavyFaint,
    },
    statValue: {
      marginTop: 0,
      fontSize: 20,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    statCaption: {
      marginTop: 2,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: onNavyFaint,
    },
  });

export const makeDashboardBodyStyles = (theme: Theme) =>
  StyleSheet.create({
    section: { paddingHorizontal: 16, marginTop: 12 },
    sectionLabel: {
      marginBottom: 12,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      padding: 20,
    },
    todayCard: { alignItems: 'center', paddingVertical: 28 },
    todayIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    todayTitle: {
      marginTop: 14,
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    todayText: {
      marginTop: 6,
      paddingHorizontal: 8,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    listCard: { padding: 0, overflow: 'hidden' },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    rowDivider: {
      height: 1,
      marginLeft: 60,
      backgroundColor: theme.colors.divider,
    },
    statusDone: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: theme.colors.green,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusTodo: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 1.5,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowBody: { flex: 1 },
    rowTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    rowSub: {
      marginTop: 2,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    hoursRow: { flexDirection: 'row', alignItems: 'center', gap: 14 },
    hoursIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.colors.warningBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    hoursTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    hoursSub: {
      marginTop: 2,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    sectionHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    sectionHeadLabel: {
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    sectionHeadMeta: {
      fontSize: 11,
      fontFamily: theme.fonts.mono,
      letterSpacing: 0.4,
      color: theme.colors.textMuted,
    },
    jobRow: { flexDirection: 'row' },
    jobAccentBar: { width: 4 },
    jobRowContent: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    jobDivider: { height: 1, backgroundColor: theme.colors.divider },
    jobTimeCol: { width: 78, alignItems: 'flex-start', gap: 6 },
    jobTime: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    jobEircode: {
      fontSize: 11,
      letterSpacing: 0.3,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
    },
    jobTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    permCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      margin: 16,
      marginBottom:4,
      borderRadius: 12,
      backgroundColor: theme.colors.warningBg,
      borderWidth: 1,
      borderColor: theme.colors.warning,
    },
    permIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surface,
    },
    permBody: { flex: 1 },
    permTitle: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    permText: {
      marginTop: 2,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },

    quickCard: { padding: 12 },
    quickCardSpacer: { marginTop: 12 },
    leaveIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    progressFillLeave: {
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.secondary,
    },
    leaveMeta: {
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.4,
      color: theme.colors.secondary,
    },
    quickTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    quickBody: { flex: 1, gap: 10 },
    quickTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    quickTitle: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    runningWrap: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    runningDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    runningText: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.6,
      color: theme.colors.textMuted,
    },
    progressTrack: {
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.borderMuted,
      overflow: 'hidden',
    },
    progressFill: {
      height: 8,
      borderRadius: 4,
      backgroundColor: theme.colors.primary,
    },
    vanCard: {
      backgroundColor: theme.colors.secondary,
      borderRadius: 16,
      padding: 16,
      gap: 14,
    },
    vanTop: { flexDirection: 'row', alignItems: 'center', gap: 14 },
    vanIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    vanTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    vanSub: {
      marginTop: 2,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: onNavyMuted,
    },
    vanBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      height: 48,
      borderRadius: 12,
      backgroundColor: theme.colors.primary,
    },
    vanBtnText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.onPrimary,
    },
  });
