import { StyleSheet } from 'react-native';

import type { Theme } from '@/theme';

export const makeFleetStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      paddingHorizontal: 20,
      paddingBottom: 14,
    },
    headerEyebrow: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    headerTitle: {
      marginTop: 4,
      fontSize: theme.typography.size.xxl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    headerSub: {
      marginTop: 2,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    emptyWrap: { paddingHorizontal: 20, gap: 16, flexGrow: 1 },
    emptyCard: {
      alignItems: 'center',
      paddingVertical: 44,
      paddingHorizontal: 28,
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      gap: 6,
    },
    emptyIcon: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: theme.colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    emptyTitle: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    emptyText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    panelContent: { paddingHorizontal: 20, paddingTop: 4, gap: 14 },
    reportBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: theme.radii.lg,
      backgroundColor: theme.colors.primary,
    },
    reportBannerBody: { flex: 1, gap: 2 },
    reportBannerTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.onPrimary,
    },
    reportBannerSub: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.onPrimary,
      opacity: 0.75,
    },
    statsRow: { flexDirection: 'row', gap: 10 },
    statCard: {
      flex: 1,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 2,
    },
    statValue: {
      fontSize: theme.typography.size.xl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    statValueAlert: { color: theme.colors.error },
    statLabel: {
      fontSize: 9,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      color: theme.colors.textMuted,
    },
    filterPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      alignSelf: 'stretch',
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
    },
    filterText: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    sectionLabel: {
      marginTop: 6,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    card: {
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      padding: 14,
      gap: 10,
    },
    cardTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: theme.radii.sm,
      backgroundColor: theme.colors.warningBg,
    },
    badgeText: {
      fontSize: 9,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      color: theme.colors.warning,
    },
    badgeGreen: { backgroundColor: '#E5F0E9' },
    badgeGreenText: { color: theme.colors.green },
    badgeRed: { backgroundColor: theme.colors.errorBg },
    badgeRedText: { color: theme.colors.error },
    badgeNeutral: { backgroundColor: theme.colors.surfaceMuted },
    badgeNeutralText: { color: theme.colors.textMuted },
    cardTopMeta: {
      flex: 1,
      textAlign: 'right',
      fontSize: 9,
      fontFamily: theme.fonts.mono,
      letterSpacing: 0.4,
      color: theme.colors.textMuted,
    },
    cardTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    cardBody: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      lineHeight: 20,
    },
    cardPhotoRow: { flexDirection: 'row', gap: 8 },
    cardPhoto: {
      width: 64,
      height: 64,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surfaceMuted,
    },
    cardFooter: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.4,
      color: theme.colors.textMuted,
    },
    historyCard: {
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
    },
    historyRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      paddingVertical: 14,
    },
    historyDivider: { height: 1, backgroundColor: theme.colors.divider },
    historyCheck: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: theme.colors.green,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    historyBody: { flex: 1, gap: 4 },
    historyTopRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    historyTitle: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    historySub: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    emptySection: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      paddingVertical: 6,
    },
  });

export default makeFleetStyles;
