import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme';

const onNavyMuted = 'rgba(255,255,255,0.62)';
const onNavyFaint = 'rgba(255,255,255,0.45)';
const trackNavy = 'rgba(255,255,255,0.14)';
const BAND = 'rgba(22,52,90,0.10)';

export const makeLeaveStyles = (theme: Theme) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: theme.colors.background },
    centered: { alignItems: 'center', justifyContent: 'center' },
    scrollContent: { flexGrow: 1 },
    body: {
      flexGrow: 1,
      backgroundColor: theme.colors.background,
      paddingBottom: 8,
    },
  });

export const makeLeaveHeaderStyles = (theme: Theme) =>
  StyleSheet.create({
    header: {
      paddingHorizontal: 20,
      paddingBottom: 4,
    },
    eyebrow: {
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.primary,
    },
    title: {
      marginTop: 2,
      fontSize: theme.typography.size.xxl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 18,
      gap: 12,
    },
    card: {
      flexBasis: '47%',
      flexGrow: 1,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
    },
    cardNavy: {
      backgroundColor: theme.colors.secondary,
      borderColor: theme.colors.secondary,
    },
    cardLabel: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1,
      color: theme.colors.textMuted,
    },
    cardLabelOnNavy: { color: theme.colors.primary },
    cardValueRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 6,
      marginTop: 8,
    },
    cardValue: {
      fontSize: 26,
      lineHeight: 28,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    cardValueOnNavy: { color: theme.colors.white },
    cardCaption: {
      marginBottom: 3,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    cardCaptionOnNavy: { color: onNavyMuted },
    cardTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: BAND,
      overflow: 'hidden',
      marginTop: 12,
    },
    cardTrackOnNavy: { backgroundColor: trackNavy },
    cardFill: { height: 6, borderRadius: 3 },
    cardSubCaption: {
      marginTop: 12,
      fontSize: 9,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      color: theme.colors.textMuted,
    },
    cardSubCaptionOnNavy: { color: onNavyFaint },
    requestBtn: {
      marginTop: 16,
      height: 52,
      borderRadius: 14,
      backgroundColor: theme.colors.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    requestBtnText: {
      fontSize: 16,
      fontFamily: theme.fonts.bold,
      color: theme.colors.onPrimary,
    },
  });

export const makeLeaveBodyStyles = (theme: Theme) =>
  StyleSheet.create({
    filterRow: {
      flexDirection: 'row',
      gap: 12,
      paddingHorizontal: 16,
      marginTop: 20,
    },
    countText: {
      paddingHorizontal: 16,
      marginTop: 16,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1,
      color: theme.colors.textMuted,
    },
    group: { paddingHorizontal: 16, marginTop: 18 },
    groupLabel: {
      marginBottom: 10,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      overflow: 'hidden',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      padding: 14,
    },
    rowDivider: {
      height: 1,
      marginLeft: 14,
      backgroundColor: theme.colors.divider,
    },
    dot: { width: 8, height: 8, borderRadius: 4, marginTop: 6 },
    rowBody: { flex: 1 },
    rowTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    rowRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    rowTitle: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    rowTitleDays: {
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    rowDate: {
      marginTop: 3,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.text,
    },
    rowMeta: {
      marginTop: 2,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    rowNote: {
      marginTop: 4,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      fontStyle: 'italic',
      color: theme.colors.textMuted,
    },
    rowNoteRejected: { color: theme.colors.error },
    emptyCard: {
      marginHorizontal: 16,
      marginTop: 20,
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      alignItems: 'center',
      paddingVertical: 34,
      paddingHorizontal: 26,
    },
    emptyIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyTitle: {
      marginTop: 16,
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    emptyText: {
      marginTop: 6,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    errorIcon: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: theme.colors.errorBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    retryBtn: {
      marginTop: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.background,
    },
    retryText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
  });

export const makeLeaveDropdownStyles = (theme: Theme) =>
  StyleSheet.create({
    wrap: { flex: 1 },
    trigger: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: theme.radii.md,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
    },
    triggerOpen: { borderColor: theme.colors.secondary },
    triggerLabel: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    triggerValueRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginTop: 3,
    },
    triggerValue: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    scrim: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(239, 234, 224, 0.55)',
    },
    panel: {
      position: 'absolute',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      paddingVertical: 6,
      overflow: 'hidden',
      shadowColor: theme.colors.black,
      shadowOpacity: 0.1,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    },
    option: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    optionActive: { backgroundColor: theme.colors.warningBg },
    optionLabel: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.medium,
      color: theme.colors.text,
    },
    optionLabelActive: { fontFamily: theme.fonts.bold },
    optionCount: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
    },
    optionCountActive: { color: theme.colors.primary },
  });

export const makeLeaveDetailStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 12,
    },
    backBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: theme.typography.size.xl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    content: { paddingHorizontal: 16, paddingBottom: 28, gap: 22 },
    card: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      padding: 16,
    },
    summaryTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    summaryTypeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    dot: { width: 8, height: 8, borderRadius: 4 },
    summaryType: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    summaryDates: {
      marginTop: 12,
      fontSize: theme.typography.size.xl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    summaryMeta: {
      marginTop: 6,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    sectionLabel: {
      marginBottom: 10,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    detailCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      paddingHorizontal: 16,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingVertical: 13,
    },
    detailDivider: {
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.divider,
    },
    detailLabel: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    detailValue: {
      flexShrink: 1,
      textAlign: 'right',
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    noteText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      fontStyle: 'italic',
      lineHeight: 20,
      color: theme.colors.text,
    },
    declineCard: {
      backgroundColor: theme.colors.errorBg,
      borderColor: theme.colors.error,
    },
    declineText: { color: theme.colors.error },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      gap: 10,
    },
    cancelBtn: {
      height: 52,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: theme.colors.error,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    cancelBtnText: {
      fontSize: 16,
      fontFamily: theme.fonts.bold,
      color: theme.colors.error,
    },
  });

export const makeNewLeaveStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 12,
    },
    headerTitle: {
      fontSize: theme.typography.size.xl,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    cancel: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.textMuted,
    },
    content: { paddingHorizontal: 16, paddingBottom: 28, gap: 22 },
    sectionLabel: {
      marginBottom: 12,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    typeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
    typeCard: {
      flexBasis: '47%',
      flexGrow: 1,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    typeCardActive: {
      backgroundColor: theme.colors.secondary,
      borderColor: theme.colors.secondary,
    },
    typeName: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    typeNameActive: { color: theme.colors.white },
    typeTag: {
      marginTop: 4,
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    typeTagActive: { color: 'rgba(255,255,255,0.7)' },
    banner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: theme.colors.primary,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    bannerNum: {
      fontSize: 28,
      fontFamily: theme.fonts.bold,
      color: theme.colors.black,
    },
    bannerText: {
      flex: 1,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.text,
      lineHeight: 19,
    },
    calCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      padding: 14,
      gap: 10,
    },
    calNav: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    calNavBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },
    calMonth: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    weekRow: { flexDirection: 'row' },
    weekday: {
      width: `${100 / 7}%`,
      textAlign: 'center',
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.5,
      color: theme.colors.textMuted,
    },
    grid: { flexDirection: 'row', flexWrap: 'wrap' },
    cell: {
      width: `${100 / 7}%`,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cellPress: {
      width: '100%',
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    bandFull: {
      position: 'absolute',
      top: 4,
      bottom: 4,
      left: 0,
      right: 0,
      backgroundColor: BAND,
    },
    bandRight: {
      position: 'absolute',
      top: 4,
      bottom: 4,
      left: '50%',
      right: 0,
      backgroundColor: BAND,
    },
    bandLeft: {
      position: 'absolute',
      top: 4,
      bottom: 4,
      left: 0,
      right: '50%',
      backgroundColor: BAND,
    },
    dayCircle: {
      width: 36,
      height: 36,
      borderRadius: theme.radii.pill,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayCircleSel: { backgroundColor: theme.colors.secondary },
    dayText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.text,
    },
    dayTextRange: { fontFamily: theme.fonts.semibold },
    dayTextSel: { color: theme.colors.white, fontFamily: theme.fonts.bold },
    dayTextMuted: { color: theme.colors.disabledText },
    calSummary: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      borderTopWidth: 1,
      borderTopColor: theme.colors.divider,
      paddingTop: 12,
    },
    calSummaryText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    calSummaryDays: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.6,
      color: theme.colors.textMuted,
    },
    calCaption: {
      textAlign: 'center',
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      color: theme.colors.textMuted,
    },
    note: { minHeight: 96, textAlignVertical: 'top' },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      gap: 10,
    },
    footerNote: {
      textAlign: 'center',
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
  });
