import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme';

export const ONB = {
  navy: '#16345A',
  cream: '#F4EFE4',
  paper: '#FFFFFF',
  muted: '#6B7382',
  line: '#E2DDCF',
  line2: '#D5CFBE',
  cardLine: '#E6E2D6',
  amber: '#E89B2D',
  amberSoft: '#FBE9C7',
};

export const makeOnboardingStyles = (theme: Theme) =>
  StyleSheet.create({
    shell: { flex: 1, backgroundColor: ONB.cream },
    topMark: { alignItems: 'center', paddingTop: 18 },

    stepRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingTop: 8,
      paddingHorizontal: 22,
    },
    stepTrack: {
      flex: 1,
      height: 4,
      borderRadius: 2,
      overflow: 'hidden',
      backgroundColor: ONB.line,
    },
    stepFill: { height: '100%', borderRadius: 2, backgroundColor: ONB.amber },
    stepLabel: {
      fontFamily: theme.fonts.mono,
      fontSize: 10,
      letterSpacing: 0.8,
      color: ONB.muted,
    },

    heading: { marginTop: 24, paddingHorizontal: 32 },
    title: {
      fontSize: 28,
      lineHeight: 32.2,
      fontFamily: theme.fonts.bold,
      letterSpacing: -0.4,
      color: ONB.navy,
      textAlign: 'center',
      includeFontPadding: false,
    },
    sub: {
      marginTop: 12,
      fontSize: 15,
      lineHeight: 21.75,
      fontFamily: theme.fonts.regular,
      color: ONB.navy,
      opacity: 0.92,
      textAlign: 'center',
    },
    subStrong: { fontFamily: theme.fonts.bold },

    spacer: { flex: 1 },
    ctas: {
      paddingHorizontal: 22,
      paddingBottom: 56,
      alignItems: 'center',
      gap: 18,
    },
    actionStack: {
      paddingHorizontal: 22,
      paddingBottom: 56,
      alignItems: 'center',
      gap: 12,
    },

    amberBtn: {
      width: '100%',
      height: 52,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: ONB.amber,
    },
    amberBtnText: {
      fontSize: 16,
      fontFamily: theme.fonts.semibold,
      letterSpacing: 0.1,
      color: ONB.navy,
    },
    outlineBtn: {
      width: '100%',
      height: 52,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: ONB.paper,
      borderWidth: 1.5,
      borderColor: ONB.navy,
    },
    outlineBtnText: {
      fontSize: 16,
      fontFamily: theme.fonts.semibold,
      letterSpacing: 0.1,
      color: ONB.navy,
    },
    btnOff: { opacity: 0.5 },
    link: {
      fontSize: 14,
      fontFamily: theme.fonts.semibold,
      color: ONB.navy,
      textDecorationLine: 'underline',
    },

    card: {
      borderWidth: 1,
      borderColor: ONB.cardLine,
      borderRadius: 14,
      backgroundColor: ONB.paper,
      padding: 18,
      gap: 14,
      shadowColor: '#0E1A2D',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    identRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      gap: 12,
    },
    identLabel: {
      fontFamily: theme.fonts.mono,
      fontSize: 12,
      letterSpacing: 0.96,
      color: ONB.muted,
    },
    identValue: {
      flex: 1,
      textAlign: 'right',
      fontSize: 14,
      fontFamily: theme.fonts.semibold,
      color: ONB.navy,
    },
    identValueMono: { fontFamily: theme.fonts.mono },
    divider: { height: 1, backgroundColor: ONB.line },

    codeRow: { flexDirection: 'row', gap: 8, justifyContent: 'center' },
    codeBox: {
      width: 46,
      height: 56,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: ONB.cardLine,
      backgroundColor: ONB.paper,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#0E1A2D',
      shadowOpacity: 0.06,
      shadowRadius: 4,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    codeBoxActive: { borderColor: ONB.navy },
    codeText: {
      fontFamily: theme.fonts.monoBold,
      fontSize: 24,
      color: ONB.navy,
      includeFontPadding: false,
    },

    meterRow: {
      flexDirection: 'row',
      gap: 4,
      height: 4,
      borderRadius: 2,
      overflow: 'hidden',
    },
    meterSeg: { flex: 1, borderRadius: 2, backgroundColor: ONB.line },
    meterSegOn: { backgroundColor: ONB.amber },
    meterLabels: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    meterText: {
      fontSize: 12,
      fontFamily: theme.fonts.regular,
      color: ONB.navy,
    },
    meterValue: { fontFamily: theme.fonts.semibold },

    checkRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    checkDot: {
      width: 18,
      height: 18,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: ONB.paper,
      borderWidth: 1.5,
      borderColor: ONB.line2,
    },
    checkDotOn: {
      backgroundColor: ONB.amber,
      borderWidth: 0,
    },
    checkLabel: { fontSize: 13, fontFamily: theme.fonts.regular, color: ONB.muted },
    checkLabelOn: { fontFamily: theme.fonts.medium, color: ONB.navy },

    fieldLabel: {
      fontSize: 13,
      fontFamily: theme.fonts.medium,
      color: ONB.navy,
      marginBottom: 6,
    },
    input: {
      height: 46,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: ONB.line2,
      backgroundColor: ONB.paper,
      paddingHorizontal: 14,
      fontSize: 16,
      fontFamily: theme.fonts.regular,
      color: ONB.navy,
    },
    inputFocused: { borderColor: ONB.navy },
    inputRow: { justifyContent: 'center' },
    inputIcon: { position: 'absolute', right: 14, zIndex: 1, elevation: 1 },
    inputWithIcon: { paddingRight: 44 },

    hero: { paddingTop: 32, paddingHorizontal: 22, alignItems: 'center' },
    heroSuccess: { paddingTop: 48, paddingHorizontal: 22, alignItems: 'center' },
    banner: { marginTop: 16, marginHorizontal: 22 },
  });

export default makeOnboardingStyles;
