import { StyleSheet } from 'react-native';

import type { Theme } from '@/theme';

export const makeReportVanIssueStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    headerBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    backBtn: {
      width: 38,
      height: 38,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerSpacer: { width: 38 },
    headerCenter: { flex: 1, alignItems: 'center' },
    headerEyebrow: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    headerTitle: {
      marginTop: 2,
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    content: { padding: 20, paddingBottom: 40, gap: 10 },
    label: {
      marginTop: 8,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
    },
    pillValue: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    pillMeta: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    input: {
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    textArea: { minHeight: 110, textAlignVertical: 'top' },
    drivableRow: { flexDirection: 'row', gap: 10 },
    drivableCard: {
      flex: 1,
      gap: 2,
      padding: 12,
      borderRadius: theme.radii.md,
      borderWidth: 1.5,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
    },
    drivableCardOnYes: {
      borderColor: theme.colors.green,
      backgroundColor: '#E5F0E9',
    },
    drivableCardOnNo: {
      borderColor: theme.colors.error,
      backgroundColor: theme.colors.errorBg,
    },
    drivableTitle: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    drivableSub: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    photoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    photoThumb: {
      width: 86,
      height: 86,
      borderRadius: theme.radii.md,
      overflow: 'hidden',
      backgroundColor: theme.colors.surfaceMuted,
    },
    photoImg: { width: '100%', height: '100%' },
    photoRemove: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: 'rgba(10,15,26,0.65)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    photoAddTile: {
      width: 86,
      height: 86,
      borderRadius: theme.radii.md,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    photoAddText: {
      fontSize: 10,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.background,
      gap: 10,
    },
    tagline: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.4,
      textAlign: 'center',
      color: theme.colors.textMuted,
    },
    sheetBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    sheetCard: {
      backgroundColor: theme.colors.background,
      borderTopLeftRadius: theme.radii.lg,
      borderTopRightRadius: theme.radii.lg,
      padding: 20,
      paddingBottom: 32,
    },
    sheetTitle: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
      marginBottom: 8,
    },
    sheetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
    },
    sheetRowText: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    sheetRowActive: {
      fontFamily: theme.fonts.bold,
      color: theme.colors.primary,
    },
    noVanWrap: { padding: 20 },
  });

export default makeReportVanIssueStyles;
