import { StyleSheet } from 'react-native';

import type { Theme } from '@/theme';

export const makeServiceScheduleStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    headerBar: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingBottom: 12,
    },
    backBtn: {
      width: 38,
      height: 38,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerSpacer: { width: 38 },
    headerCenter: { flex: 1, alignItems: 'center' },
    headerEyebrow: {
      fontSize: 10,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.4,
      color: theme.colors.textMuted,
    },
    headerTitle: {
      marginTop: 2,
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    content: { padding: 20, paddingBottom: 40, gap: 10 },
    label: {
      marginTop: 8,
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
    },
    pillValue: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    pillPlaceholder: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.placeholder,
    },
    pillMeta: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    input: {
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    textArea: { minHeight: 90, textAlignVertical: 'top' },
    segmentRow: { flexDirection: 'row', gap: 8 },
    segment: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 11,
      borderRadius: theme.radii.md,
      borderWidth: 1.5,
      borderColor: theme.colors.borderMuted,
      backgroundColor: theme.colors.surface,
    },
    segmentOn: {
      borderColor: theme.colors.primary,
      backgroundColor: theme.colors.warningBg,
    },
    segmentText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.textMuted,
    },
    segmentTextOn: { color: theme.colors.text },
    intervalRow: { flexDirection: 'row', gap: 10 },
    intervalCell: { flex: 1, gap: 6 },
    nextDueCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 14,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
    },
    nextDueBody: { flex: 1, gap: 2 },
    nextDueValue: {
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    nextDueHint: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      lineHeight: 17,
    },
    footer: {
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.background,
      gap: 10,
    },
    sheetBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    sheetCard: {
      backgroundColor: theme.colors.background,
      borderTopLeftRadius: theme.radii.lg,
      borderTopRightRadius: theme.radii.lg,
      padding: 20,
      paddingBottom: 28,
      maxHeight: '82%',
    },
    sheetTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 8,
    },
    sheetTitle: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    sheetAction: {
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 0.8,
      color: theme.colors.secondary,
    },
    sheetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 12,
    },
    sheetRowBody: { flex: 1, gap: 2 },
    sheetRowText: {
      flex: 1,
      fontSize: theme.typography.size.md,
      fontFamily: theme.fonts.regular,
      color: theme.colors.text,
    },
    sheetRowActive: {
      fontFamily: theme.fonts.bold,
      color: theme.colors.primary,
    },
    sheetRowMeta: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    sheetIconBtn: {
      width: 32,
      height: 32,
      borderRadius: theme.radii.sm,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
    },
    sheetDivider: { height: 1, backgroundColor: theme.colors.divider },
    sheetEmpty: {
      paddingVertical: 14,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
    },
    editorCard: {
      marginTop: 12,
      padding: 14,
      borderRadius: theme.radii.md,
      borderWidth: 1,
      borderColor: theme.colors.creamBorder,
      backgroundColor: theme.colors.surface,
      gap: 10,
    },
    editorTitle: {
      fontSize: 11,
      fontFamily: theme.fonts.monoBold,
      letterSpacing: 1.2,
      color: theme.colors.textMuted,
    },
    editorRow: { flexDirection: 'row', gap: 10 },
    editorBtns: { flexDirection: 'row', gap: 10 },
    editorBtn: { flex: 1 },
    hint: {
      fontSize: theme.typography.size.xs,
      fontFamily: theme.fonts.regular,
      color: theme.colors.textMuted,
      lineHeight: 17,
    },
  });

export default makeServiceScheduleStyles;
