import { StyleSheet } from 'react-native';
import type { Theme } from '@/theme';

export const makeTimesheetStyles = (theme: Theme) =>
  StyleSheet.create({
    flex: { flex: 1, backgroundColor: theme.colors.background },
    centered: { alignItems: 'center', justifyContent: 'center' },

    header: {
      backgroundColor: theme.colors.secondary,
      paddingHorizontal: 20,
      paddingBottom: 22,
    },
    headTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    eyebrow: {
      fontSize: 11,
      letterSpacing: 1.5,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.white,
      opacity: 0.6,
    },
    title: {
      marginTop: 6,
      fontSize: 24,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    monthRow: {
      marginTop: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    monthPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(255,255,255,0.12)',
      borderRadius: theme.radii.pill,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    monthPillText: {
      color: theme.colors.white,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
    },
    arrowBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(255,255,255,0.12)',
    },
    arrows: { flexDirection: 'row', gap: 8 },

    totalValue: {
      marginTop: 18,
      fontSize: 34,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    totalSub: {
      marginTop: 2,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.white,
      opacity: 0.7,
    },

    content: { paddingHorizontal: 20, paddingTop: 18 },
    sectionLabel: {
      marginBottom: 12,
      fontSize: 11,
      letterSpacing: 1.5,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
    },

    dayRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radii.lg,
      borderWidth: 1,
      borderColor: theme.colors.borderMuted,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
    },
    dayDateCol: { width: 38, alignItems: 'center' },
    dayWeekday: {
      fontSize: 10,
      letterSpacing: 1,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.textMuted,
    },
    dayNum: {
      fontSize: 20,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    dayBody: { flex: 1 },
    dayMeta: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.text,
    },
    dayBarTrack: {
      marginTop: 8,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.surfaceMuted,
      overflow: 'hidden',
    },
    dayBarFill: {
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.primary,
    },
    dayHours: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
    },
    dayHoursMuted: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
      color: theme.colors.placeholder,
    },
    leaveTag: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      gap: 6,
      backgroundColor: theme.colors.surfaceMuted,
      borderRadius: theme.radii.pill,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    leaveTagText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.secondary,
    },
    leaveSpacer: { height: 8 },

    restRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 10,
    },
    restText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.placeholder,
    },

    empty: { alignItems: 'center', paddingHorizontal: 32, paddingTop: 64 },
    emptyIcon: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.surfaceMuted,
      marginBottom: 16,
    },
    emptyTitle: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.text,
      textAlign: 'center',
    },
    emptyText: {
      marginTop: 8,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.medium,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },

    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
    },
    pickerCard: {
      backgroundColor: theme.colors.secondary,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 28,
    },
    handle: {
      alignSelf: 'center',
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: 'rgba(255,255,255,0.25)',
      marginBottom: 18,
    },
    pickerHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    pickerLabel: {
      fontSize: 11,
      letterSpacing: 1.5,
      fontFamily: theme.fonts.monoBold,
      color: theme.colors.white,
      opacity: 0.6,
    },
    yearNav: { flexDirection: 'row', alignItems: 'center', gap: 14 },
    yearNavValue: {
      fontSize: theme.typography.size.lg,
      fontFamily: theme.fonts.bold,
      color: theme.colors.white,
    },
    grid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
    },
    gridItem: {
      width: '31%',
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.07)',
    },
    gridItemOn: { backgroundColor: theme.colors.white },
    gridItemText: {
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.semibold,
      color: theme.colors.white,
    },
    gridItemTextOn: { color: theme.colors.secondary },
    doneBtn: {
      marginTop: 22,
      backgroundColor: theme.colors.primary,
      borderRadius: theme.radii.pill,
      paddingVertical: 15,
      alignItems: 'center',
    },
    doneBtnText: {
      color: theme.colors.onPrimary,
      fontSize: theme.typography.size.sm,
      fontFamily: theme.fonts.bold,
    },
  });
