export const palette = {
  yellow: '#E89B2D',
  navy: '#16345A',
  white: '#FFFFFF',
  black: '#0A0F1A',
  cream: '#EFEAE0',
  green: '#017636',
  creamSurface: '#F7F4EC',
  creamBorder: '#E6DFCF',
  greyborder: '#d2d4d6',
  red: '#D14343',
  redTint: '#FBEAEA',
  amber: '#B7791F',
  amberTint: '#FBF1DD',
  gray50: '#F7F8F9',
  gray100: '#EFF1F3',
  gray200: '#E3E6E9',
  gray300: '#CFD4DA',
  gray400: '#A7AEB6',
  gray500: '#8A929C',
  gray600: '#5C6571',
};

export const lightColors = {
  primary: palette.yellow,
  onPrimary: palette.navy,
  creamBorder: palette.creamBorder,
  green: palette.green,
  secondary: palette.navy,
  onSecondary: palette.white,
  background: palette.cream,
  surface: palette.white,
  surfaceMuted: palette.gray100,
  text: palette.navy,
  textMuted: palette.gray600,
  border: palette.navy,
  borderMuted: palette.gray200,
  inputBackground: palette.white,
  inputBorder: palette.greyborder,
  placeholder: palette.gray400,
  error: palette.red,
  errorBg: palette.redTint,
  warning: palette.amber,
  warningBg: palette.amberTint,
  disabledBg: palette.gray100,
  disabledBorder: palette.gray200,
  disabledText: palette.gray400,
  divider: palette.gray200,
  white: palette.white,
  black: palette.black,
};

export type AppColors = typeof lightColors;
